# Passwordless Login - Symfony Routes

wepresta_passwordless_login_configure:
    path: /wepresta_passwordless_login/configure
    methods: [GET]
    defaults:
        _controller: 'Wepresta_Passwordless_Login\Presentation\Controller\Admin\ConfigureRedirectController::index'
        _legacy_controller: AdminWepresta_Passwordless_LoginMain
        _legacy_link: AdminWepresta_Passwordless_LoginMain
